__values = [
    {'key': 'USD', 'value': 'Dólar Americano'},
    {'key': 'EUR', 'value': 'Euro'},
    {'key': 'JPY', 'value': 'Iene Japonês'},
    {'key': 'GBP', 'value': 'Libra Esterlina'},
    {'key': 'CHF', 'value': 'Franco Suíço'},
    {'key': 'INR', 'value': 'Rupia Indiana'},
    {'key': 'RUB', 'value': 'Rublo Russo'},
    {'key': 'THB', 'value': 'Baht Tailandês'},
    {'key': 'TRY', 'value': 'Lira Turca'},
    {'key': 'CRC', 'value': 'Colón Costarriquenho'},
    {'key': 'UAH', 'value': 'Hryvnia Ucraniano'},
    {'key': 'MNT', 'value': 'Tugrik Mongol'},
    {'key': 'KRW', 'value': 'Won Sul-coreano'},
    {'key': 'NGN', 'value': 'Naira Nigeriana'},
    {'key': 'ILS', 'value': 'Novo Shekel Israelense'},
    {'key': 'VND', 'value': 'Dong Vietnamita'},
    {'key': 'KHR', 'value': 'Riel Cambojano'},
    {'key': 'GEL', 'value': 'Lari Georgiano'},
    {'key': 'PYG', 'value': 'Guarani Paraguaio'},
    {'key': 'GHS', 'value': 'Cedi Ganês'},
    {'key': 'AZN', 'value': 'Manat Azerbaijano'},
    {'key': 'PHP', 'value': 'Peso Filipino'},
    {'key': 'PKR', 'value': 'Rupia Paquistanesa'},
    {'key': 'LAK', 'value': 'Kip Laosiano'},
    {'key': 'GRD', 'value': 'Dracma Grego'},
    {'key': 'BRL', 'value': 'Real Brasileiro'},
    {'key': 'FRF', 'value': 'Franco Francês'},
    {'key': 'ESP', 'value': 'Peseta Espanhola'},
    {'key': 'BHD', 'value': 'Dinar Bahreiniano'},
    {'key': 'SAR', 'value': 'Rial Saudita'},
    {'key': 'KWD', 'value': 'Dinar Kuwaitiano'},
    {'key': 'AED', 'value': 'Dirham dos Emirados Árabes Unidos'},
    {'key': 'QAR', 'value': 'Rial Catariano'},
    {'key': 'OMR', 'value': 'Rial Omani'},
    {'key': 'JOD', 'value': 'Dinar Jordaniano'},
    {'key': 'EGP', 'value': 'Libra Egípcia'},
    {'key': 'ZAR', 'value': 'Rand Sul-africano'},
    {'key': 'CAD', 'value': 'Dólar Canadense'},
    {'key': 'AUD', 'value': 'Dólar Australiano'},
    {'key': 'NZD', 'value': 'Dólar da Nova Zelândia'},
    {'key': 'SGD', 'value': 'Dólar de Singapura'},
    {'key': 'MYR', 'value': 'Ringgit Malaio'},
    {'key': 'IDR', 'value': 'Rupia Indonésia'},
    {'key': 'CNY', 'value': 'Yuan Chinês'},
    {'key': 'HKD', 'value': 'Dólar de Hong Kong'},
    {'key': 'TWD', 'value': 'Novo Dólar de Taiwan'}
]

def getCurrencies():
    return __values
